export interface AllTimeTrackSeed {
  artist: string;
  title: string;
  genre: string;
}

export const ARGENTINA_ALL_TIME_TRACKS: AllTimeTrackSeed[] = [
  { artist: "Soda Stereo", title: "De Música Ligera", genre: "Rock" },
  { artist: "Gustavo Cerati", title: "Crimen", genre: "Rock" },
  { artist: "Charly García", title: "Demoliendo Hoteles", genre: "Rock" },
  { artist: "Fito Páez", title: "El Amor Después del Amor", genre: "Rock" },
  { artist: "Luis Alberto Spinetta", title: "Seguir Viviendo Sin Tu Amor", genre: "Rock" },
  { artist: "Los Fabulosos Cadillacs", title: "Matador", genre: "Rock" },
  { artist: "Patricio Rey y sus Redonditos de Ricota", title: "Ji Ji Ji", genre: "Rock" },
  { artist: "Sumo", title: "La Rubia Tarada", genre: "Rock" },
  { artist: "Divididos", title: "Spaghetti del Rock", genre: "Rock" },
  { artist: "La Renga", title: "El Final Es En Donde Partí", genre: "Rock" },
  { artist: "Los Piojos", title: "Verano del 92", genre: "Rock" },
  { artist: "Andrés Calamaro", title: "Flaca", genre: "Rock" },
  { artist: "Babasónicos", title: "Irresponsables", genre: "Alternativa" },
  { artist: "Catupecu Machu", title: "Y Lo Que Quiero Es Que Pises Sin el Suelo", genre: "Rock" },
  { artist: "Ratones Paranoicos", title: "Rock del Gato", genre: "Rock" },
  { artist: "Attaque 77", title: "Hacelo Por Mí", genre: "Rock" },
  { artist: "Los Abuelos de la Nada", title: "Mil Horas", genre: "Rock" },
  { artist: "Virus", title: "Pronta Entrega", genre: "Rock" },
  { artist: "Serú Girán", title: "Seminare", genre: "Rock" },
  { artist: "Sui Generis", title: "Rasguña las Piedras", genre: "Rock" },
  { artist: "Almendra", title: "Muchacha Ojos de Papel", genre: "Rock" },
  { artist: "Pappo", title: "Juntos a la Par", genre: "Rock" },
  { artist: "Riff", title: "No Detenga Su Motor", genre: "Rock" },
  { artist: "Vox Dei", title: "Presente", genre: "Rock" },
  { artist: "La Bersuit Vergarabat", title: "Sr. Cobranza", genre: "Rock" },
  { artist: "Kapanga", title: "El Mono Relojero", genre: "Rock" },
  { artist: "Las Pelotas", title: "Será", genre: "Rock" },
  { artist: "Intoxicados", title: "Fuego", genre: "Rock" },
  { artist: "Viejas Locas", title: "Me Gustas Mucho", genre: "Rock" },
  { artist: "Airbag", title: "Por Mil Noches", genre: "Rock" },
  { artist: "Miranda!", title: "Don", genre: "Pop" },
  { artist: "Lali", title: "Disciplina", genre: "Pop" },
  { artist: "Tini", title: "Miénteme", genre: "Pop" },
  { artist: "Emilia", title: "No_se_ve.mp3", genre: "Pop" },
  { artist: "María Becerra", title: "Automático", genre: "Pop" },
  { artist: "Nicki Nicole", title: "Wapo Traketero", genre: "Hip-Hop" },
  { artist: "Diego Torres", title: "Color Esperanza", genre: "Pop" },
  { artist: "Axel", title: "Celebra la Vida", genre: "Pop" },
  { artist: "Abel Pintos", title: "Sin Principio Ni Final", genre: "Pop" },
  { artist: "Soledad", title: "Tren del Cielo", genre: "Latin" },
  { artist: "Duki", title: "Goteo", genre: "Hip-Hop" },
  { artist: "Wos", title: "Canguro", genre: "Hip-Hop" },
  { artist: "Trueno", title: "Dance Crip", genre: "Hip-Hop" },
  { artist: "Paulo Londra", title: "Adán y Eva", genre: "Hip-Hop" },
  { artist: "Lit Killah", title: "Flexin'", genre: "Hip-Hop" },
  { artist: "Khea", title: "Loca", genre: "Hip-Hop" },
  { artist: "Tiago PZK", title: "Entre Nosotros", genre: "Hip-Hop" },
  { artist: "Dillom", title: "OPA", genre: "Hip-Hop" },
  { artist: "Bizarrap", title: "Quevedo: Bzrp Music Sessions, Vol. 52", genre: "Hip-Hop" },
  { artist: "Nathy Peluso", title: "Buenos Aires", genre: "Hip-Hop" },
  { artist: "Damas Gratis", title: "No Te Creas Tan Importante", genre: "Latin" },
  { artist: "Ráfaga", title: "Mentirosa", genre: "Latin" },
  { artist: "Los Palmeras", title: "Bombón Asesino", genre: "Latin" },
  { artist: "Rodrigo", title: "La Mano de Dios", genre: "Latin" },
  { artist: "La Mona Jiménez", title: "Beso a Beso", genre: "Latin" },
  { artist: "Ulises Bueno", title: "Intento", genre: "Latin" },
  { artist: "Gilda", title: "No Me Arrepiento de Este Amor", genre: "Latin" },
  { artist: "Leo Mattioli", title: "Le Pido a Dios", genre: "Latin" },
  { artist: "Amar Azul", title: "Yo Tomo", genre: "Latin" },
  { artist: "Yerba Brava", title: "La Cumbia de los Trapos", genre: "Latin" },
  { artist: "Mercedes Sosa", title: "Gracias a la Vida", genre: "Latin" },
  { artist: "Los Chalchaleros", title: "Zamba de Mi Esperanza", genre: "Latin" },
  { artist: "Atahualpa Yupanqui", title: "Los Ejes de Mi Carreta", genre: "Latin" },
  { artist: "Jorge Cafrune", title: "Zamba de Mi Esperanza", genre: "Latin" },
  { artist: "Horacio Guarany", title: "Si Se Calla el Cantor", genre: "Latin" },
  { artist: "Los Nocheros", title: "Entre la Tierra y el Cielo", genre: "Latin" },
  { artist: "Chaqueño Palavecino", title: "Amor Salvaje", genre: "Latin" },
  { artist: "Carlos Gardel", title: "Volver", genre: "Latin" },
  { artist: "Astor Piazzolla", title: "Libertango", genre: "Latin" },
  { artist: "Gotan Project", title: "Santa María", genre: "Electrónica" },
  { artist: "Bajofondo", title: "Pa' Bailar", genre: "Electrónica" },
  { artist: "Los Pericos", title: "Pupilas Lejanas", genre: "Reggae" },
  { artist: "Los Cafres", title: "Tus Ojos", genre: "Reggae" },
  { artist: "Mimi Maura", title: "No No No", genre: "Reggae" },
  { artist: "Gato Barbieri", title: "Europa", genre: "Jazz" },
  { artist: "Pedro Aznar", title: "A Primera Vista", genre: "Jazz" },
  { artist: "Kevin Johansen", title: "Anoche Soñé Contigo", genre: "Alternativa" },
  { artist: "El Kuelgue", title: "Circunvalación", genre: "Alternativa" },
  { artist: "Él Mató a un Policía Motorizado", title: "El Tesoro", genre: "Alternativa" },
  { artist: "Massacre", title: "La Reina de Marte", genre: "Alternativa" },
  { artist: "Eruca Sativa", title: "Magoo", genre: "Rock" },
  { artist: "Connor Questa", title: "Pensar Bien", genre: "Rock" },
  { artist: "Cielo Razzo", title: "Luminoso", genre: "Rock" },
  { artist: "Guasones", title: "Reyes de la Noche", genre: "Rock" },
  { artist: "El Bordo", title: "Cansado de Ser", genre: "Rock" },
  { artist: "Pier", title: "Sacrificio y Rock'n Roll", genre: "Rock" },
  { artist: "Los Tipitos", title: "Brujería", genre: "Rock" },
  { artist: "Estelares", title: "Ella Dijo", genre: "Rock" },
  { artist: "Árbol", title: "Pequeños Sueños", genre: "Rock" },
  { artist: "La Mancha de Rolando", title: "Calavera", genre: "Rock" },
  { artist: "Los Auténticos Decadentes", title: "La Guitarra", genre: "Latin" },
  { artist: "Los Caligaris", title: "Razón", genre: "Latin" },
  { artist: "Karina", title: "Con la Misma Moneda", genre: "Latin" },
  { artist: "Abel Pintos", title: "Oncemil", genre: "Pop" },
  { artist: "Fabiana Cantilo", title: "Mi Enfermedad", genre: "Rock" },
  { artist: "Celeste Carballo", title: "Me Vuelvo Cada Día Más Loca", genre: "Rock" },
  { artist: "Sandra Mihanovich", title: "Puerto Pollensa", genre: "Pop" },
  { artist: "Valeria Lynch", title: "Me Das Cada Día Más", genre: "Pop" },
  { artist: "Pimpinela", title: "Olvídame y Pega la Vuelta", genre: "Pop" },
  { artist: "A.N.I.M.A.L.", title: "Loco Pro", genre: "Rock" },
  { artist: "Los Enanitos Verdes", title: "Lamento Boliviano", genre: "Rock" },
  { artist: "Miguel Mateos", title: "Cuando Seas Grande", genre: "Rock" },
  { artist: "Zas", title: "Tirá Para Arriba", genre: "Rock" },
  { artist: "Rata Blanca", title: "Mujer Amante", genre: "Rock" },
  { artist: "Los Violadores", title: "Uno Dos Ultraviolento", genre: "Rock" },
  { artist: "Todos Tus Muertos", title: "Andate", genre: "Rock" },
  { artist: "2 Minutos", title: "Ya No Sos Igual", genre: "Rock" },
  { artist: "Callejeros", title: "Una Nueva Noche Fría", genre: "Rock" },
  { artist: "La 25", title: "Solo Voy", genre: "Rock" },
  { artist: "Jóvenes Pordioseros", title: "Nunca Me Enseñaste", genre: "Rock" },
  { artist: "Turf", title: "Loco un Poco", genre: "Rock" },
  { artist: "Las Pastillas del Abuelo", title: "El Sensei", genre: "Rock" },
];

export const INTERNATIONAL_ALL_TIME_TRACKS: AllTimeTrackSeed[] = [
  { artist: "Queen", title: "Bohemian Rhapsody", genre: "Rock" },
  { artist: "The Beatles", title: "Hey Jude", genre: "Rock" },
  { artist: "Michael Jackson", title: "Billie Jean", genre: "Pop" },
  { artist: "Madonna", title: "Like a Prayer", genre: "Pop" },
  { artist: "Prince", title: "Purple Rain", genre: "Pop" },
  { artist: "Nirvana", title: "Smells Like Teen Spirit", genre: "Rock" },
  { artist: "Led Zeppelin", title: "Stairway to Heaven", genre: "Rock" },
  { artist: "The Rolling Stones", title: "Paint It Black", genre: "Rock" },
  { artist: "Pink Floyd", title: "Wish You Were Here", genre: "Rock" },
  { artist: "Bob Dylan", title: "Like a Rolling Stone", genre: "Rock" },
  { artist: "David Bowie", title: "Heroes", genre: "Rock" },
  { artist: "Elton John", title: "Rocket Man", genre: "Pop" },
  { artist: "Whitney Houston", title: "I Will Always Love You", genre: "R&B / Soul" },
  { artist: "Aretha Franklin", title: "Respect", genre: "R&B / Soul" },
  { artist: "Stevie Wonder", title: "Superstition", genre: "R&B / Soul" },
  { artist: "Marvin Gaye", title: "What's Going On", genre: "R&B / Soul" },
  { artist: "The Beach Boys", title: "Good Vibrations", genre: "Pop" },
  { artist: "ABBA", title: "Dancing Queen", genre: "Pop" },
  { artist: "Eagles", title: "Hotel California", genre: "Rock" },
  { artist: "Fleetwood Mac", title: "Dreams", genre: "Rock" },
  { artist: "U2", title: "With or Without You", genre: "Rock" },
  { artist: "The Police", title: "Every Breath You Take", genre: "Rock" },
  { artist: "Bon Jovi", title: "Livin' On a Prayer", genre: "Rock" },
  { artist: "Guns N' Roses", title: "Sweet Child O' Mine", genre: "Rock" },
  { artist: "AC/DC", title: "Back In Black", genre: "Rock" },
  { artist: "Metallica", title: "Enter Sandman", genre: "Rock" },
  { artist: "Radiohead", title: "Creep", genre: "Alternativa" },
  { artist: "Oasis", title: "Wonderwall", genre: "Alternativa" },
  { artist: "Coldplay", title: "Yellow", genre: "Alternativa" },
  { artist: "Red Hot Chili Peppers", title: "Under the Bridge", genre: "Alternativa" },
  { artist: "The Cure", title: "Friday I'm In Love", genre: "Alternativa" },
  { artist: "Depeche Mode", title: "Enjoy the Silence", genre: "Electrónica" },
  { artist: "Daft Punk", title: "One More Time", genre: "Dance" },
  { artist: "Bee Gees", title: "Stayin' Alive", genre: "Dance" },
  { artist: "Donna Summer", title: "I Feel Love", genre: "Dance" },
  { artist: "Gloria Gaynor", title: "I Will Survive", genre: "Dance" },
  { artist: "Earth, Wind & Fire", title: "September", genre: "R&B / Soul" },
  { artist: "Toto", title: "Africa", genre: "Rock" },
  { artist: "Journey", title: "Don't Stop Believin'", genre: "Rock" },
  { artist: "The Killers", title: "Mr. Brightside", genre: "Alternativa" },
  { artist: "Beyoncé", title: "Crazy in Love", genre: "Pop" },
  { artist: "Britney Spears", title: "...Baby One More Time", genre: "Pop" },
  { artist: "Lady Gaga", title: "Bad Romance", genre: "Pop" },
  { artist: "Rihanna", title: "Umbrella", genre: "Pop" },
  { artist: "Adele", title: "Rolling in the Deep", genre: "Pop" },
  { artist: "Taylor Swift", title: "Shake It Off", genre: "Pop" },
  { artist: "Bruno Mars", title: "Uptown Funk", genre: "Pop" },
  { artist: "The Weeknd", title: "Blinding Lights", genre: "Pop" },
  { artist: "Ed Sheeran", title: "Shape of You", genre: "Pop" },
  { artist: "Ariana Grande", title: "Thank U, Next", genre: "Pop" },
  { artist: "Eminem", title: "Lose Yourself", genre: "Hip-Hop" },
  { artist: "Dr. Dre", title: "Still D.R.E.", genre: "Hip-Hop" },
  { artist: "Tupac", title: "California Love", genre: "Hip-Hop" },
  { artist: "The Notorious B.I.G.", title: "Juicy", genre: "Hip-Hop" },
  { artist: "Jay-Z", title: "Empire State of Mind", genre: "Hip-Hop" },
  { artist: "Kanye West", title: "Stronger", genre: "Hip-Hop" },
  { artist: "Kendrick Lamar", title: "HUMBLE.", genre: "Hip-Hop" },
  { artist: "Outkast", title: "Hey Ya!", genre: "Hip-Hop" },
  { artist: "Lauryn Hill", title: "Doo Wop", genre: "Hip-Hop" },
  { artist: "Snoop Dogg", title: "Gin and Juice", genre: "Hip-Hop" },
  { artist: "Bob Marley", title: "No Woman, No Cry", genre: "Reggae" },
  { artist: "Peter Tosh", title: "Legalize It", genre: "Reggae" },
  { artist: "UB40", title: "Red Red Wine", genre: "Reggae" },
  { artist: "Shakira", title: "Hips Don't Lie", genre: "Latin" },
  { artist: "Ricky Martin", title: "Livin' la Vida Loca", genre: "Latin" },
  { artist: "Luis Miguel", title: "Ahora Te Puedes Marchar", genre: "Latin" },
  { artist: "Juanes", title: "La Camisa Negra", genre: "Latin" },
  { artist: "Maná", title: "Rayando el Sol", genre: "Latin" },
  { artist: "Enrique Iglesias", title: "Bailando", genre: "Latin" },
  { artist: "Gloria Estefan", title: "Conga", genre: "Latin" },
  { artist: "Daddy Yankee", title: "Gasolina", genre: "Latin" },
  { artist: "Bad Bunny", title: "Tití Me Preguntó", genre: "Latin" },
  { artist: "J Balvin", title: "Mi Gente", genre: "Latin" },
  { artist: "Miles Davis", title: "So What", genre: "Jazz" },
  { artist: "John Coltrane", title: "My Favorite Things", genre: "Jazz" },
  { artist: "Louis Armstrong", title: "What a Wonderful World", genre: "Jazz" },
  { artist: "Ella Fitzgerald", title: "Summertime", genre: "Jazz" },
  { artist: "Frank Sinatra", title: "My Way", genre: "Jazz" },
  { artist: "Johnny Cash", title: "Ring of Fire", genre: "Country" },
  { artist: "Dolly Parton", title: "Jolene", genre: "Country" },
  { artist: "Willie Nelson", title: "On the Road Again", genre: "Country" },
  { artist: "Kenny Rogers", title: "The Gambler", genre: "Country" },
  { artist: "Garth Brooks", title: "Friends In Low Places", genre: "Country" },
  { artist: "Beethoven", title: "Symphony No. 5", genre: "Clásica" },
  { artist: "Mozart", title: "Eine kleine Nachtmusik", genre: "Clásica" },
  { artist: "Bach", title: "Toccata and Fugue in D Minor", genre: "Clásica" },
  { artist: "Vivaldi", title: "The Four Seasons", genre: "Clásica" },
  { artist: "Tchaikovsky", title: "Swan Lake", genre: "Clásica" },
  { artist: "Simon & Garfunkel", title: "The Sound of Silence", genre: "Rock" },
  { artist: "The Doors", title: "Light My Fire", genre: "Rock" },
  { artist: "Jimi Hendrix", title: "All Along the Watchtower", genre: "Rock" },
  { artist: "The Clash", title: "London Calling", genre: "Rock" },
  { artist: "Sex Pistols", title: "Anarchy In the U.K.", genre: "Rock" },
  { artist: "R.E.M.", title: "Losing My Religion", genre: "Alternativa" },
  { artist: "Green Day", title: "Basket Case", genre: "Rock" },
  { artist: "Linkin Park", title: "In the End", genre: "Rock" },
  { artist: "Amy Winehouse", title: "Rehab", genre: "R&B / Soul" },
  { artist: "Alicia Keys", title: "Fallin'", genre: "R&B / Soul" },
  { artist: "Usher", title: "Yeah!", genre: "R&B / Soul" },
  { artist: "Pharrell Williams", title: "Happy", genre: "Pop" },
  { artist: "Cyndi Lauper", title: "Girls Just Want to Have Fun", genre: "Pop" },
];
